version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - redis
    # environment:
    #   - CELERY_BROKER_URL=redis://crossbow-redis-1:6379/0
    #   - CELERY_RESULT_BACKEND=redis://crossbow-redis-1:6379/0
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    networks:
      - crossbow-network

  celery:
    build: .
    command: celery -A core worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    # environment:
    #   - CELERY_BROKER_URL=redis://crossbow-redis-1:6379/0
    #   - CELERY_RESULT_BACKEND=redis://crossbow-redis-1:6379/0
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    networks:
      - crossbow-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - crossbow-network

networks:
  crossbow-network:
    driver: bridge 