# Generated by Django 5.2.1 on 2025-05-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_subscription_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverylog',
            name='event_type',
            field=models.CharField(blank=True, help_text='The event type that triggered this delivery', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='event_types',
            field=models.TextField(default='order.created', help_text='Comma-separated list of event types this subscription is interested in'),
        ),
        migrations.AddIndex(
            model_name='deliverylog',
            index=models.Index(fields=['event_type'], name='deliveries__event_t_e6062d_idx'),
        ),
    ]
